version: "3.8"
services:
  next:
    container_name: next
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: npm run dev
    ports:
      - 3000:3000
